# Site settings
title: lmf
# the subpath baseurl must be to be publish & working in production under lmf.ch
# if you want to preview the website under username.github.io/lmf, you have to change baseurl to /lmf
baseurl: "/lmf"
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [node_modules, gulp-config.json, Gulpfile.js, package.json, webpack-config.js, package-lock.json, README.md]